### ISSUE TITLE
Got stuck after a bomb hit me

### ISSUE THREAD

**Issue by bnjox** [DavidMatthewFraser/zombie-hero#1]
## Version

* Phaser Version:

* Operating system:

* Browser: Firefox

## Description

Got stuck on one side after a bomb hit me, 
![zombie-hero](https://user-images.githubusercontent.com/61359802/102871392-49ae1400-4436-11eb-9d3d-16f72dbc5f36.gif)

## Additional Information
Nice game by the way

**Comment by DavidMatthewFraser** [comment]
Thanks Benji!
That's expected behavior ... the game currently just ends when you collide with a bomb. 
But yea, I should change that ;)
BTW, you can make something like this by following this guide: http://phaser.io/tutorials/making-your-first-phaser-3-game/part1
Feel free to make any PRs if you want

**Comment by bnjox** [comment]
Cool, I will be playing It when I'm online.
I like the game, I'll try to make one
